[phases.setup]
nixPkgs = ["postgresql"]

[phases.install]
cmds = [
    "pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "python manage.py collectstatic --noinput",
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

[processes]
web = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"

[environment]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "config.settings" 