[phases.setup]
nixPkgs = [
    "python311",
    "python311Packages.pip",
    "python311Packages.setuptools",
    "python311Packages.wheel",
    "python311Packages.psycopg2",
    "python311Packages.gunicorn",
    "postgresql",
    "gcc",
    "libpqxx"
]

[phases.install]
cmds = [
    "export PATH=/nix/store/*-python3-3.11.9/bin:$PATH",
    "python3 -m ensurepip --upgrade",
    "python3 -m pip install --upgrade pip",
    "python3 -m pip install -r requirements.txt",
]

[phases.build]
cmds = [
    "python3 manage.py collectstatic --noinput",
    "python3 manage.py migrate",
]

[start]
cmd = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"

[processes]
web = "gunicorn config.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120"

[environment]
PYTHONUNBUFFERED = "1"
DJANGO_SETTINGS_MODULE = "config.settings"
PYTHONPATH = "/app"
DJANGO_DEBUG = "False"
DJANGO_ALLOWED_HOSTS = "*"
DATABASE_URL = "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}"
PATH = "/nix/store/*-python3-3.11.9/bin:$PATH" 